#!/usr/bin/env bash
# instalation of Nginx
apt-get update
apt-get -y install Nginx
ufw allow 'Nginx HTTP'
chmod u+w index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start
