#!/usr/bin/env bash
# instalation of Nginx
sudo apt-get -y install Nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod u+w index.nginx-debian.html
echo 'Holberton School' > '/var/www/html/index.nginx-debian.html'