#!/usr/bin/env bash
# instalation of Nginx
apt-get update
apt-get -y install Nginx
ufw allow 'Nginx HTTP'
chmod u+w index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 /a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i '38a \ \tlocation / {\n\tadd_header X-Served-By $HOSTNAME;\n\t}\n' $file
service nginx start