#!/usr/bin/env bash
# instalation of Nginx
#shellcheck disable=SC2154
apt-get update
apt-get -y install Nginx
ufw allow 'Nginx HTTP'
chmod u+w index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/http {\a add_header X-Served-By ${HOSTNAME};}" /etc/nginx/nginx.conf
service nginx start