#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i="1"
while [ $i -lt 11 ]
do
if [ "$i" != "9" ]; then
	echo "Holberton School"
	i=$((i+1))
else
	echo "Hi"
	i=$((i+1))
fi
done
