#!/usr/bin/env bash
#Fix a container so that Nginx is running as the nginx user.

sudo pkill apache2
sudo chmod 700 /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
